package com.wt.jiaduo.dto;
// Generated 2018-3-31 15:55:00 by Hibernate Tools 5.2.8.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * SysPermission generated by hbm2java
 */
@Entity
@Table(name = "sys_permission", catalog = "jiaduo")
public class SysPermission implements java.io.Serializable {

	private Integer id;
	private String name;
	private String type;
	private String url;
	private String percode;
	private Long parentid;
	private String parentids;
	private String sortstring;
	private Character available;

	public SysPermission() {
	}

	public SysPermission(String name, String type) {
		this.name = name;
		this.type = type;
	}

	public SysPermission(String name, String type, String url, String percode, Long parentid, String parentids,
			String sortstring, Character available) {
		this.name = name;
		this.type = type;
		this.url = url;
		this.percode = percode;
		this.parentid = parentid;
		this.parentids = parentids;
		this.sortstring = sortstring;
		this.available = available;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name", nullable = false, length = 128)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "type", nullable = false, length = 32)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@Column(name = "url", length = 128)
	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	@Column(name = "percode", length = 128)
	public String getPercode() {
		return this.percode;
	}

	public void setPercode(String percode) {
		this.percode = percode;
	}

	@Column(name = "parentid")
	public Long getParentid() {
		return this.parentid;
	}

	public void setParentid(Long parentid) {
		this.parentid = parentid;
	}

	@Column(name = "parentids", length = 128)
	public String getParentids() {
		return this.parentids;
	}

	public void setParentids(String parentids) {
		this.parentids = parentids;
	}

	@Column(name = "sortstring", length = 128)
	public String getSortstring() {
		return this.sortstring;
	}

	public void setSortstring(String sortstring) {
		this.sortstring = sortstring;
	}

	@Column(name = "available", length = 1)
	public Character getAvailable() {
		return this.available;
	}

	public void setAvailable(Character available) {
		this.available = available;
	}

}
