package com.wt.jiaduo.dto;
// Generated 2018-3-31 15:55:00 by Hibernate Tools 5.2.8.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * SysRole generated by hbm2java
 */
@Entity
@Table(name = "sys_role", catalog = "jiaduo")
public class SysRole implements java.io.Serializable {

	private Integer id;
	private String name;
	private Character available;

	public SysRole() {
	}

	public SysRole(String name) {
		this.name = name;
	}

	public SysRole(String name, Character available) {
		this.name = name;
		this.available = available;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name", nullable = false, length = 128)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "available", length = 1)
	public Character getAvailable() {
		return this.available;
	}

	public void setAvailable(Character available) {
		this.available = available;
	}

}
