package com.wt.jiaduo.dto;
// Generated 2018-3-31 15:55:00 by Hibernate Tools 5.2.8.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * SysRolePermission generated by hbm2java
 */
@Entity
@Table(name = "sys_role_permission", catalog = "jiaduo")
public class SysRolePermission implements java.io.Serializable {

	private SysRolePermissionId id;

	public SysRolePermission() {
	}

	public SysRolePermission(SysRolePermissionId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "sysRoleId", column = @Column(name = "sys_role_id", nullable = false)),
			@AttributeOverride(name = "sysPermissionId", column = @Column(name = "sys_permission_id", nullable = false)) })
	public SysRolePermissionId getId() {
		return this.id;
	}

	public void setId(SysRolePermissionId id) {
		this.id = id;
	}

}
