package com.wt.jiaduo.dto;
// Generated 2018-3-31 9:23:34 by Hibernate Tools 5.2.8.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * XiaomaiSanheisuibing generated by hbm2java
 */
@Entity
@Table(name = "xiaomai_sanheisuibing", catalog = "jiaduo")
public class XiaomaiSanheisuibing implements java.io.Serializable {

	private Integer id;
	private Date dateTime;
	private String place;
	private String person;
	private String varietyName;
	private String representativeArea;
	private String surveyPointnum;
	private String diseasePointnum;
	private String diseasepointRate;
	private String surveyMaiyenum;
	private String diseaseMaiyenum;
	private String diseasemaiyeRate;
	private String remark;
	private Integer userId;
	private String userName;
	private String longitude;
	private String latitude;

	public XiaomaiSanheisuibing() {
	}

	public XiaomaiSanheisuibing(Date dateTime, String place, String person, String varietyName,
			String representativeArea, String surveyPointnum, String diseasePointnum, String diseasepointRate,
			String surveyMaiyenum, String diseaseMaiyenum, String diseasemaiyeRate, String remark, Integer userId,
			String userName, String longitude, String latitude) {
		this.dateTime = dateTime;
		this.place = place;
		this.person = person;
		this.varietyName = varietyName;
		this.representativeArea = representativeArea;
		this.surveyPointnum = surveyPointnum;
		this.diseasePointnum = diseasePointnum;
		this.diseasepointRate = diseasepointRate;
		this.surveyMaiyenum = surveyMaiyenum;
		this.diseaseMaiyenum = diseaseMaiyenum;
		this.diseasemaiyeRate = diseasemaiyeRate;
		this.remark = remark;
		this.userId = userId;
		this.userName = userName;
		this.longitude = longitude;
		this.latitude = latitude;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date_time", length = 19)
	public Date getDateTime() {
		return this.dateTime;
	}

	public void setDateTime(Date dateTime) {
		this.dateTime = dateTime;
	}

	@Column(name = "place")
	public String getPlace() {
		return this.place;
	}

	public void setPlace(String place) {
		this.place = place;
	}

	@Column(name = "person")
	public String getPerson() {
		return this.person;
	}

	public void setPerson(String person) {
		this.person = person;
	}

	@Column(name = "variety_name")
	public String getVarietyName() {
		return this.varietyName;
	}

	public void setVarietyName(String varietyName) {
		this.varietyName = varietyName;
	}

	@Column(name = "representative_area")
	public String getRepresentativeArea() {
		return this.representativeArea;
	}

	public void setRepresentativeArea(String representativeArea) {
		this.representativeArea = representativeArea;
	}

	@Column(name = "survey_pointnum")
	public String getSurveyPointnum() {
		return this.surveyPointnum;
	}

	public void setSurveyPointnum(String surveyPointnum) {
		this.surveyPointnum = surveyPointnum;
	}

	@Column(name = "disease_pointnum")
	public String getDiseasePointnum() {
		return this.diseasePointnum;
	}

	public void setDiseasePointnum(String diseasePointnum) {
		this.diseasePointnum = diseasePointnum;
	}

	@Column(name = "diseasepoint_rate")
	public String getDiseasepointRate() {
		return this.diseasepointRate;
	}

	public void setDiseasepointRate(String diseasepointRate) {
		this.diseasepointRate = diseasepointRate;
	}

	@Column(name = "survey_maiyenum")
	public String getSurveyMaiyenum() {
		return this.surveyMaiyenum;
	}

	public void setSurveyMaiyenum(String surveyMaiyenum) {
		this.surveyMaiyenum = surveyMaiyenum;
	}

	@Column(name = "disease_maiyenum")
	public String getDiseaseMaiyenum() {
		return this.diseaseMaiyenum;
	}

	public void setDiseaseMaiyenum(String diseaseMaiyenum) {
		this.diseaseMaiyenum = diseaseMaiyenum;
	}

	@Column(name = "diseasemaiye_rate")
	public String getDiseasemaiyeRate() {
		return this.diseasemaiyeRate;
	}

	public void setDiseasemaiyeRate(String diseasemaiyeRate) {
		this.diseasemaiyeRate = diseasemaiyeRate;
	}

	@Column(name = "remark")
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	@Column(name = "user_id")
	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	@Column(name = "user_name")
	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	@Column(name = "longitude")
	public String getLongitude() {
		return this.longitude;
	}

	public void setLongitude(String longitude) {
		this.longitude = longitude;
	}

	@Column(name = "latitude")
	public String getLatitude() {
		return this.latitude;
	}

	public void setLatitude(String latitude) {
		this.latitude = latitude;
	}

}
