package com.wt.jiaduo.dao.controller.pojovalid;
// Generated 2018-3-30 18:10:03 by Hibernate Tools 5.2.8.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * SysRolePermissionId generated by hbm2java
 */
@Embeddable
public class SysRolePermissionId implements java.io.Serializable {

	private int sysRoleId;
	private int sysPermissionId;

	public SysRolePermissionId() {
	}

	public SysRolePermissionId(int sysRoleId, int sysPermissionId) {
		this.sysRoleId = sysRoleId;
		this.sysPermissionId = sysPermissionId;
	}

	@Column(name = "sys_role_id", nullable = false)
	public int getSysRoleId() {
		return this.sysRoleId;
	}

	public void setSysRoleId(int sysRoleId) {
		this.sysRoleId = sysRoleId;
	}

	@Column(name = "sys_permission_id", nullable = false)
	public int getSysPermissionId() {
		return this.sysPermissionId;
	}

	public void setSysPermissionId(int sysPermissionId) {
		this.sysPermissionId = sysPermissionId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof SysRolePermissionId))
			return false;
		SysRolePermissionId castOther = (SysRolePermissionId) other;

		return (this.getSysRoleId() == castOther.getSysRoleId())
				&& (this.getSysPermissionId() == castOther.getSysPermissionId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getSysRoleId();
		result = 37 * result + this.getSysPermissionId();
		return result;
	}

}
