package com.wt.jiaduo.dao.controller.pojovalid;
// Generated 2018-3-30 18:10:03 by Hibernate Tools 5.2.8.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * XiaomaiCongaibingYoucepufabinglv generated by hbm2java
 */
@Entity
@Table(name = "xiaomai_congaibing_youcepufabinglv", catalog = "jiaduo")
public class XiaomaiCongaibingYoucepufabinglvUpdateValid implements java.io.Serializable {

	private Integer id;
	private Date dateTime;
	private String person;
	private String place;
	private String qianchazuowu;
	private String xiaomaipinzhong;
	private String buzhongriqi;
	private String diaochamiaoshu;
	private String fabingmiaoshu;
	private String bingzhulv;
	private String remark;
	private Integer userId;
	private String userName;
	private String longitude;
	private String latitude;

	public XiaomaiCongaibingYoucepufabinglvUpdateValid() {
	}

	public XiaomaiCongaibingYoucepufabinglvUpdateValid(Date dateTime, String person, String place, String qianchazuowu,
			String xiaomaipinzhong, String buzhongriqi, String diaochamiaoshu, String fabingmiaoshu, String bingzhulv,
			String remark, Integer userId, String userName, String longitude, String latitude) {
		this.dateTime = dateTime;
		this.person = person;
		this.place = place;
		this.qianchazuowu = qianchazuowu;
		this.xiaomaipinzhong = xiaomaipinzhong;
		this.buzhongriqi = buzhongriqi;
		this.diaochamiaoshu = diaochamiaoshu;
		this.fabingmiaoshu = fabingmiaoshu;
		this.bingzhulv = bingzhulv;
		this.remark = remark;
		this.userId = userId;
		this.userName = userName;
		this.longitude = longitude;
		this.latitude = latitude;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date_time", length = 19)
	public Date getDateTime() {
		return this.dateTime;
	}

	public void setDateTime(Date dateTime) {
		this.dateTime = dateTime;
	}

	@Column(name = "person")
	public String getPerson() {
		return this.person;
	}

	public void setPerson(String person) {
		this.person = person;
	}

	@Column(name = "place")
	public String getPlace() {
		return this.place;
	}

	public void setPlace(String place) {
		this.place = place;
	}

	@Column(name = "qianchazuowu")
	public String getQianchazuowu() {
		return this.qianchazuowu;
	}

	public void setQianchazuowu(String qianchazuowu) {
		this.qianchazuowu = qianchazuowu;
	}

	@Column(name = "xiaomaipinzhong")
	public String getXiaomaipinzhong() {
		return this.xiaomaipinzhong;
	}

	public void setXiaomaipinzhong(String xiaomaipinzhong) {
		this.xiaomaipinzhong = xiaomaipinzhong;
	}

	@Column(name = "buzhongriqi")
	public String getBuzhongriqi() {
		return this.buzhongriqi;
	}

	public void setBuzhongriqi(String buzhongriqi) {
		this.buzhongriqi = buzhongriqi;
	}

	@Column(name = "diaochamiaoshu")
	public String getDiaochamiaoshu() {
		return this.diaochamiaoshu;
	}

	public void setDiaochamiaoshu(String diaochamiaoshu) {
		this.diaochamiaoshu = diaochamiaoshu;
	}

	@Column(name = "fabingmiaoshu")
	public String getFabingmiaoshu() {
		return this.fabingmiaoshu;
	}

	public void setFabingmiaoshu(String fabingmiaoshu) {
		this.fabingmiaoshu = fabingmiaoshu;
	}

	@Column(name = "bingzhulv")
	public String getBingzhulv() {
		return this.bingzhulv;
	}

	public void setBingzhulv(String bingzhulv) {
		this.bingzhulv = bingzhulv;
	}

	@Column(name = "remark")
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	@Column(name = "user_id")
	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	@Column(name = "user_name")
	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	@Column(name = "longitude")
	public String getLongitude() {
		return this.longitude;
	}

	public void setLongitude(String longitude) {
		this.longitude = longitude;
	}

	@Column(name = "latitude")
	public String getLatitude() {
		return this.latitude;
	}

	public void setLatitude(String latitude) {
		this.latitude = latitude;
	}

}
