package com.wt.jiaduo.utils.mybatisgenerator;

public class TableNameGenerateCreateSequence {
	public static void main(String[] args) {

		String start = "CREATE SEQUENCE  \"";
		String end = "\"  MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE";
		String[] arr = { "USER_ROLE",
				"UNIT",
				"PERMISSION",
				"ROLE_PERMISSION",
				"ROLE",
				"LAW_BEHAVIOR_EXTENTS",
				"LAW_BEHAVIORS",
				"GP_REVIPROC_CASESTATE",
				"GP_DECISION_APPROVAL",
				"GP_FILING",
				"ZFTYPES",
				"USER_ZFTYPE",
				"USER_CONF_CASES",
				"USERS",
				"TEST",
				"SUPERVISION_TYPES",
				"SUPERVISE_SUPERVISION_TYPE",
				"SUPERVISE_RUN_MODE",
				"SUPERVISES",
				"SIMPLE_PROGRAM_PRODUCT",
				"SIMPLE_PROGRAM",
				"RUN_MODES",
				"PUNISHMENT_TYPE",
				"MEASURE_UNIT_SPECI",
				"MEASURE_UNIT_MONE",
				"MEASUREMENT_UNIT",
				"LAW_BEHAVIOR_CATEGORIES",
				"LAWCHECKLIST_PROD",
				"LAWCHECKLIST_PLACE",
				"LAWCHECKLIST_CATE_CONT",
				"LAWCHECKLIST_CATE_BEHA",
				"LAWCHECKLIST_CATE",
				"LAWCHECKLIST",
				"INPUT_RECORD",
				"GP_TRANSFER_ATTA",
				"GP_TRANSFER",
				"GP_SOURCE",
				"GP_SERVICE_RECEIPT_INST",
				"GP_SERVICE_RECEIPT",
				"GP_ROLLING_TABLE",
				"GP_ROLLING_REMARK",
				"GP_ROLLING_PUNI",
				"GP_REVIPROC_PUNIDISC",
				"GP_REVIPROC_MAJOR_PUNIDISC",
				"GP_PROOF_TALK_NOTICE",
				"GP_PROOF_SITERECORD",
				"GP_PROOF_SEAL_RECORD",
				"GP_PROOF_SEAL_DECI_PROD",
				"GP_PROOF_SEAL_DECI",
				"GP_PROOF_SAMPLING_PROD",
				"GP_PROOF_SAMPLING",
				"GP_PROOF_REGI_NOTICE",
				"GP_PROOF_PROD_CONFIR_PROD",
				"GP_PROOF_PROD_CONFIR",
				"GP_PROOF_PROD_CALC",
				"GP_PROOF_POWEROFATTORNEY",
				"GP_PROOF_INQUIRY",
				"GP_PROOF_IMG",
				"GP_PROOF_EVID_LIST_PROD",
				"GP_PROOF_EVID_LIST",
				"GP_PROOF_DISMI_DECI_PROD",
				"GP_PROOF_DISMI_DECI",
				"GP_PROG",
				"GP_PROD",
				"GP_PEVI_CAILIAN_PUNI",
				"GP_NOTIFY_PUNI_NOTI",
				"GP_NOTIFY_ORDER_CORR",
				"GP_HEAR_REPORT",
				"GP_HEAR_RECORD",
				"GP_HEAR_PUNI_NOTI",
				"GP_EXE_URGE",
				"GP_EXE_PENARECO",
				"GP_EXE_MANDATORY",
				"GP_DECISION_DECI",
				"GP_CLOSE_PUNIREPO",
				"GP_CLOSE_PASTE",
				"GP_CLOSE_MARJORREPO",
				"GP_CLOSE_ATTA_TYPE",
				"AREAS"

		};
		for (String ar : arr) {

			String token = ar;

			System.out.println(start + token +"_SEQ"+ end + ";");
		}
	}

}
