package com.wt.jiaduo.dto.jpa;
// Generated 2018-4-4 16:06:16 by Hibernate Tools 5.2.8.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * MalingshuPinzhong generated by hbm2java
 */
@Entity
@Table(name = "malingshu_pinzhong", catalog = "jiaduo")
public class MalingshuPinzhong implements java.io.Serializable {

	private Integer id;
	private String name;

	public MalingshuPinzhong() {
	}

	public MalingshuPinzhong(String name) {
		this.name = name;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

}
