package com.wt.jiaduo.dto.jpa;
// Generated 2018-4-3 10:51:07 by Hibernate Tools 5.2.8.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIdentityInfo;
import com.fasterxml.jackson.annotation.ObjectIdGenerators;

/**
 * SysPermission generated by hbm2java
 */
@Entity
@Table(name = "sys_permission", catalog = "jiaduo")
@JsonIdentityInfo(generator = ObjectIdGenerators.PropertyGenerator.class, property = "id")
public class SysPermission implements java.io.Serializable {

	private Integer id;
	private String name;
	private String type;
	private String url;
	private String percode;
	private Long parentid;
	private String parentids;
	private String sortstring;
	private Integer available;
	private Set<SysRolePermission> sysRolePermissions = new HashSet<>();

	@OneToMany(mappedBy = "sysPermission")
	public Set<SysRolePermission> getSysRolePermissions() {
		return sysRolePermissions;
	}

	public void setSysRolePermissions(Set<SysRolePermission> sysRolePermissions) {
		this.sysRolePermissions = sysRolePermissions;
	}

	public SysPermission() {
	}

	public SysPermission(String name, String type) {
		this.name = name;
		this.type = type;
	}

	public SysPermission(String name, String type, String url, String percode, Long parentid, String parentids,
			String sortstring, Integer available) {
		this.name = name;
		this.type = type;
		this.url = url;
		this.percode = percode;
		this.parentid = parentid;
		this.parentids = parentids;
		this.sortstring = sortstring;
		this.available = available;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name", nullable = false, length = 128)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "type", nullable = false, length = 32)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@Column(name = "url", length = 128)
	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	@Column(name = "percode", length = 128)
	public String getPercode() {
		return this.percode;
	}

	public void setPercode(String percode) {
		this.percode = percode;
	}

	@Column(name = "parentid")
	public Long getParentid() {
		return this.parentid;
	}

	public void setParentid(Long parentid) {
		this.parentid = parentid;
	}

	@Column(name = "parentids", length = 128)
	public String getParentids() {
		return this.parentids;
	}

	public void setParentids(String parentids) {
		this.parentids = parentids;
	}

	@Column(name = "sortstring", length = 128)
	public String getSortstring() {
		return this.sortstring;
	}

	public void setSortstring(String sortstring) {
		this.sortstring = sortstring;
	}

	@Column(name = "available")
	public Integer getAvailable() {
		return this.available;
	}

	public void setAvailable(Integer available) {
		this.available = available;
	}

}
