package com.wt.jiaduo.controller.pojovalid;
// Generated 2018-3-31 10:29:38 by Hibernate Tools 5.2.8.Final

import java.util.Date;

import javax.validation.constraints.NotNull;

/**
 * MalingshuWanyibingfabingqingkuang generated by hbm2java
 */
public class MalingshuWanyibingfabingqingkuangUpdateValid implements java.io.Serializable {
	@NotNull(message="id不能为空")
	private Integer id;
	private String place;
	private Date dateTime;
	private String pingzhong;
	private String tiankuaileixing;
	private String shengyuqi;
	private String diaochatiankuai;
	private String fabingtiankuai;
	private String bingtianlv;
	private String diaochazhushu;
	private String fabingzhushu;
	private String bingzhulv;
	private String remark;
	private Integer userId;
	private String userName;
	private String longitude;
	private String latitude;

	public MalingshuWanyibingfabingqingkuangUpdateValid() {
	}

	public MalingshuWanyibingfabingqingkuangUpdateValid(String place,  Date dateTime, String pingzhong,
			String tiankuaileixing, String shengyuqi, String diaochatiankuai, String fabingtiankuai, String bingtianlv,
			String diaochazhushu, String fabingzhushu, String bingzhulv, String remark, Integer userId, String userName,
			String longitude, String latitude) {
		this.place = place;
		this.dateTime = dateTime;
		this.pingzhong = pingzhong;
		this.tiankuaileixing = tiankuaileixing;
		this.shengyuqi = shengyuqi;
		this.diaochatiankuai = diaochatiankuai;
		this.fabingtiankuai = fabingtiankuai;
		this.bingtianlv = bingtianlv;
		this.diaochazhushu = diaochazhushu;
		this.fabingzhushu = fabingzhushu;
		this.bingzhulv = bingzhulv;
		this.remark = remark;
		this.userId = userId;
		this.userName = userName;
		this.longitude = longitude;
		this.latitude = latitude;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getPlace() {
		return this.place;
	}

	public void setPlace(String place) {
		this.place = place;
	}

	

	public Date getDateTime() {
		return this.dateTime;
	}

	public void setDateTime(Date dateTime) {
		this.dateTime = dateTime;
	}

	public String getPingzhong() {
		return this.pingzhong;
	}

	public void setPingzhong(String pingzhong) {
		this.pingzhong = pingzhong;
	}

	public String getTiankuaileixing() {
		return this.tiankuaileixing;
	}

	public void setTiankuaileixing(String tiankuaileixing) {
		this.tiankuaileixing = tiankuaileixing;
	}

	public String getShengyuqi() {
		return this.shengyuqi;
	}

	public void setShengyuqi(String shengyuqi) {
		this.shengyuqi = shengyuqi;
	}

	public String getDiaochatiankuai() {
		return this.diaochatiankuai;
	}

	public void setDiaochatiankuai(String diaochatiankuai) {
		this.diaochatiankuai = diaochatiankuai;
	}

	public String getFabingtiankuai() {
		return this.fabingtiankuai;
	}

	public void setFabingtiankuai(String fabingtiankuai) {
		this.fabingtiankuai = fabingtiankuai;
	}

	public String getBingtianlv() {
		return this.bingtianlv;
	}

	public void setBingtianlv(String bingtianlv) {
		this.bingtianlv = bingtianlv;
	}

	public String getDiaochazhushu() {
		return this.diaochazhushu;
	}

	public void setDiaochazhushu(String diaochazhushu) {
		this.diaochazhushu = diaochazhushu;
	}

	public String getFabingzhushu() {
		return this.fabingzhushu;
	}

	public void setFabingzhushu(String fabingzhushu) {
		this.fabingzhushu = fabingzhushu;
	}

	public String getBingzhulv() {
		return this.bingzhulv;
	}

	public void setBingzhulv(String bingzhulv) {
		this.bingzhulv = bingzhulv;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public String getLongitude() {
		return this.longitude;
	}

	public void setLongitude(String longitude) {
		this.longitude = longitude;
	}

	public String getLatitude() {
		return this.latitude;
	}

	public void setLatitude(String latitude) {
		this.latitude = latitude;
	}

}
