package com.wt.jiaduo.controller.pojovalid;
// Generated 2018-3-31 10:29:38 by Hibernate Tools 5.2.8.Final

import java.util.Date;

import javax.validation.constraints.NotNull;

/**
 * XiaomaiMaizhizhudatian generated by hbm2java
 */
public class XiaomaiMaizhizhudatianUpdateValid implements java.io.Serializable {
	@NotNull(message="id不能为空")
	private Integer id;
	private Date dateTime;
	private String place;
	private String daibiaomianji;
	private String pinzhong;
	private String shengyuqi;
	private String danxingchongliang;
	private String remark;
	private Integer userId;
	private String userName;
	private String longitude;
	private String latitude;

	public XiaomaiMaizhizhudatianUpdateValid() {
	}

	public XiaomaiMaizhizhudatianUpdateValid(Date dateTime,  String place, String daibiaomianji, String pinzhong,
			String shengyuqi, String danxingchongliang, String remark, Integer userId, String userName,
			String longitude, String latitude) {
		this.dateTime = dateTime;
		this.place = place;
		this.daibiaomianji = daibiaomianji;
		this.pinzhong = pinzhong;
		this.shengyuqi = shengyuqi;
		this.danxingchongliang = danxingchongliang;
		this.remark = remark;
		this.userId = userId;
		this.userName = userName;
		this.longitude = longitude;
		this.latitude = latitude;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Date getDateTime() {
		return this.dateTime;
	}

	public void setDateTime(Date dateTime) {
		this.dateTime = dateTime;
	}

	

	public String getPlace() {
		return this.place;
	}

	public void setPlace(String place) {
		this.place = place;
	}

	public String getDaibiaomianji() {
		return this.daibiaomianji;
	}

	public void setDaibiaomianji(String daibiaomianji) {
		this.daibiaomianji = daibiaomianji;
	}

	public String getPinzhong() {
		return this.pinzhong;
	}

	public void setPinzhong(String pinzhong) {
		this.pinzhong = pinzhong;
	}

	public String getShengyuqi() {
		return this.shengyuqi;
	}

	public void setShengyuqi(String shengyuqi) {
		this.shengyuqi = shengyuqi;
	}

	public String getDanxingchongliang() {
		return this.danxingchongliang;
	}

	public void setDanxingchongliang(String danxingchongliang) {
		this.danxingchongliang = danxingchongliang;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public String getLongitude() {
		return this.longitude;
	}

	public void setLongitude(String longitude) {
		this.longitude = longitude;
	}

	public String getLatitude() {
		return this.latitude;
	}

	public void setLatitude(String latitude) {
		this.latitude = latitude;
	}

}
