package com.wt.jiaduo.controller.pojovalid;
// Generated 2018-3-31 10:29:38 by Hibernate Tools 5.2.8.Final

import java.util.Date;

/**
 * XiaomaiCongaibingHuifeishizirandaidulv generated by hbm2java
 */
public class XiaomaiCongaibingHuifeishizirandaidulvAddValid implements java.io.Serializable {

	
	private Date dateTime;
	private String place;
	private String caichongdikuai;
	private String xiaomaipinzhong;
	private String chongtai;
	private String jiechongmiaoshu;
	private String fabingmiaoshu;
	private String daidulv;
	private String remark;
	private Integer userId;
	private String userName;
	private String longitude;
	private String latitude;

	public XiaomaiCongaibingHuifeishizirandaidulvAddValid() {
	}

	public XiaomaiCongaibingHuifeishizirandaidulvAddValid(Date dateTime,  String place, String caichongdikuai,
			String xiaomaipinzhong, String chongtai, String jiechongmiaoshu, String fabingmiaoshu, String daidulv,
			String remark, Integer userId, String userName, String longitude, String latitude) {
		this.dateTime = dateTime;
		this.place = place;
		this.caichongdikuai = caichongdikuai;
		this.xiaomaipinzhong = xiaomaipinzhong;
		this.chongtai = chongtai;
		this.jiechongmiaoshu = jiechongmiaoshu;
		this.fabingmiaoshu = fabingmiaoshu;
		this.daidulv = daidulv;
		this.remark = remark;
		this.userId = userId;
		this.userName = userName;
		this.longitude = longitude;
		this.latitude = latitude;
	}

	
	public Date getDateTime() {
		return this.dateTime;
	}

	public void setDateTime(Date dateTime) {
		this.dateTime = dateTime;
	}

	
	public String getPlace() {
		return this.place;
	}

	public void setPlace(String place) {
		this.place = place;
	}

	public String getCaichongdikuai() {
		return this.caichongdikuai;
	}

	public void setCaichongdikuai(String caichongdikuai) {
		this.caichongdikuai = caichongdikuai;
	}

	public String getXiaomaipinzhong() {
		return this.xiaomaipinzhong;
	}

	public void setXiaomaipinzhong(String xiaomaipinzhong) {
		this.xiaomaipinzhong = xiaomaipinzhong;
	}

	public String getChongtai() {
		return this.chongtai;
	}

	public void setChongtai(String chongtai) {
		this.chongtai = chongtai;
	}

	public String getJiechongmiaoshu() {
		return this.jiechongmiaoshu;
	}

	public void setJiechongmiaoshu(String jiechongmiaoshu) {
		this.jiechongmiaoshu = jiechongmiaoshu;
	}

	public String getFabingmiaoshu() {
		return this.fabingmiaoshu;
	}

	public void setFabingmiaoshu(String fabingmiaoshu) {
		this.fabingmiaoshu = fabingmiaoshu;
	}

	public String getDaidulv() {
		return this.daidulv;
	}

	public void setDaidulv(String daidulv) {
		this.daidulv = daidulv;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public String getLongitude() {
		return this.longitude;
	}

	public void setLongitude(String longitude) {
		this.longitude = longitude;
	}

	public String getLatitude() {
		return this.latitude;
	}

	public void setLatitude(String latitude) {
		this.latitude = latitude;
	}

}
