package com.wt.jiaduo.controller.pojovalid;
// Generated 2018-3-31 10:29:38 by Hibernate Tools 5.2.8.Final

import java.util.Date;

import javax.validation.constraints.NotNull;

import org.springframework.format.annotation.DateTimeFormat;

/**
 * XiaomaiChimeibing generated by hbm2java
 */
public class XiaomaiChimeibingUpdateValid implements java.io.Serializable {
	@NotNull(message="id不能为空")
	private Integer id;
	@DateTimeFormat(pattern="yyyy-MM-dd HH:mm:ss")
	private Date dateTime;
	private String place;
	private String pinzhong;
	private String leixingtian;
	private String diaochasuishu;
	private String bingsuishu;
	private String bingsuilv;
	private String bingqing0;
	private String bingqing1;
	private String bingqing2;
	private String bingqing3;
	private String bingqing4;
	private String bingqing5;
	private String bingqingzhishu;
	private String remark;
	private Integer userId;
	private String userName;
	private String longitude;
	private String latitude;

	public XiaomaiChimeibingUpdateValid() {
	}

	public XiaomaiChimeibingUpdateValid(Date dateTime,  String place, String pinzhong, String leixingtian,
			String diaochasuishu, String bingsuishu, String bingsuilv, String bingqing0, String bingqing1,
			String bingqing2, String bingqing3, String bingqing4, String bingqing5, String bingqingzhishu,
			String remark, Integer userId, String userName, String longitude, String latitude) {
		this.dateTime = dateTime;
		this.place = place;
		this.pinzhong = pinzhong;
		this.leixingtian = leixingtian;
		this.diaochasuishu = diaochasuishu;
		this.bingsuishu = bingsuishu;
		this.bingsuilv = bingsuilv;
		this.bingqing0 = bingqing0;
		this.bingqing1 = bingqing1;
		this.bingqing2 = bingqing2;
		this.bingqing3 = bingqing3;
		this.bingqing4 = bingqing4;
		this.bingqing5 = bingqing5;
		this.bingqingzhishu = bingqingzhishu;
		this.remark = remark;
		this.userId = userId;
		this.userName = userName;
		this.longitude = longitude;
		this.latitude = latitude;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Date getDateTime() {
		return this.dateTime;
	}

	public void setDateTime(Date dateTime) {
		this.dateTime = dateTime;
	}

	

	public String getPlace() {
		return this.place;
	}

	public void setPlace(String place) {
		this.place = place;
	}

	public String getPinzhong() {
		return this.pinzhong;
	}

	public void setPinzhong(String pinzhong) {
		this.pinzhong = pinzhong;
	}

	public String getLeixingtian() {
		return this.leixingtian;
	}

	public void setLeixingtian(String leixingtian) {
		this.leixingtian = leixingtian;
	}

	public String getDiaochasuishu() {
		return this.diaochasuishu;
	}

	public void setDiaochasuishu(String diaochasuishu) {
		this.diaochasuishu = diaochasuishu;
	}

	public String getBingsuishu() {
		return this.bingsuishu;
	}

	public void setBingsuishu(String bingsuishu) {
		this.bingsuishu = bingsuishu;
	}

	public String getBingsuilv() {
		return this.bingsuilv;
	}

	public void setBingsuilv(String bingsuilv) {
		this.bingsuilv = bingsuilv;
	}

	public String getBingqing0() {
		return this.bingqing0;
	}

	public void setBingqing0(String bingqing0) {
		this.bingqing0 = bingqing0;
	}

	public String getBingqing1() {
		return this.bingqing1;
	}

	public void setBingqing1(String bingqing1) {
		this.bingqing1 = bingqing1;
	}

	public String getBingqing2() {
		return this.bingqing2;
	}

	public void setBingqing2(String bingqing2) {
		this.bingqing2 = bingqing2;
	}

	public String getBingqing3() {
		return this.bingqing3;
	}

	public void setBingqing3(String bingqing3) {
		this.bingqing3 = bingqing3;
	}

	public String getBingqing4() {
		return this.bingqing4;
	}

	public void setBingqing4(String bingqing4) {
		this.bingqing4 = bingqing4;
	}

	public String getBingqing5() {
		return this.bingqing5;
	}

	public void setBingqing5(String bingqing5) {
		this.bingqing5 = bingqing5;
	}

	public String getBingqingzhishu() {
		return this.bingqingzhishu;
	}

	public void setBingqingzhishu(String bingqingzhishu) {
		this.bingqingzhishu = bingqingzhishu;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public String getLongitude() {
		return this.longitude;
	}

	public void setLongitude(String longitude) {
		this.longitude = longitude;
	}

	public String getLatitude() {
		return this.latitude;
	}

	public void setLatitude(String latitude) {
		this.latitude = latitude;
	}

}
