package com.wt.jiaduo.controller.pojovalid;
// Generated 2018-3-31 10:29:38 by Hibernate Tools 5.2.8.Final

import java.util.Date;

/**
 * XiaomaiCongaibingTianjianzishengmaimiao generated by hbm2java
 */
public class XiaomaiCongaibingTianjianzishengmaimiaoAddValid implements java.io.Serializable {

	
	private Date dateTime;
	private String place;
	private String pinzhong;
	private String diaochazhushu;
	private String fabingzhushu;
	private String bingzhulv;
	private String remark;
	private Integer userId;
	private String userName;
	private String longitude;
	private String latitude;

	public XiaomaiCongaibingTianjianzishengmaimiaoAddValid() {
	}

	public XiaomaiCongaibingTianjianzishengmaimiaoAddValid(Date dateTime,  String place, String pinzhong,
			String diaochazhushu, String fabingzhushu, String bingzhulv, String remark, Integer userId, String userName,
			String longitude, String latitude) {
		this.dateTime = dateTime;
		this.place = place;
		this.pinzhong = pinzhong;
		this.diaochazhushu = diaochazhushu;
		this.fabingzhushu = fabingzhushu;
		this.bingzhulv = bingzhulv;
		this.remark = remark;
		this.userId = userId;
		this.userName = userName;
		this.longitude = longitude;
		this.latitude = latitude;
	}

	

	public Date getDateTime() {
		return this.dateTime;
	}

	public void setDateTime(Date dateTime) {
		this.dateTime = dateTime;
	}

	

	public String getPlace() {
		return this.place;
	}

	public void setPlace(String place) {
		this.place = place;
	}

	public String getPinzhong() {
		return this.pinzhong;
	}

	public void setPinzhong(String pinzhong) {
		this.pinzhong = pinzhong;
	}

	public String getDiaochazhushu() {
		return this.diaochazhushu;
	}

	public void setDiaochazhushu(String diaochazhushu) {
		this.diaochazhushu = diaochazhushu;
	}

	public String getFabingzhushu() {
		return this.fabingzhushu;
	}

	public void setFabingzhushu(String fabingzhushu) {
		this.fabingzhushu = fabingzhushu;
	}

	public String getBingzhulv() {
		return this.bingzhulv;
	}

	public void setBingzhulv(String bingzhulv) {
		this.bingzhulv = bingzhulv;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public String getLongitude() {
		return this.longitude;
	}

	public void setLongitude(String longitude) {
		this.longitude = longitude;
	}

	public String getLatitude() {
		return this.latitude;
	}

	public void setLatitude(String latitude) {
		this.latitude = latitude;
	}

}
