package com.wt.jiaduo.controller.pojovalid;
// Generated 2018-3-31 10:29:38 by Hibernate Tools 5.2.8.Final

import java.util.Date;

import javax.validation.constraints.NotNull;

import org.springframework.format.annotation.DateTimeFormat;

/**
 * XiaomaiYachongDatian generated by hbm2java
 */
public class XiaomaiYachongDatianUpdateValid implements java.io.Serializable {
	@NotNull(message="id不能为空")
	private Integer id;
	@DateTimeFormat(pattern="yyyy-MM-dd HH:mm:ss")
	private Date dateTime;
	private String place;
	private String daibiaomianji;
	private String pinzhong;
	private String shengyuqi;
	private String diaochazhushu;
	private String youyazhushu;
	private String youyazhulv;
	private String youchiyachongshuliang;
	private String wuchiyachongshuliang;
	private String hejishuliang;
	private String baizhuyaliang;
	private String remark;
	private Integer userId;
	private String userName;
	private String longitude;
	private String latitude;

	public XiaomaiYachongDatianUpdateValid() {
	}

	public XiaomaiYachongDatianUpdateValid(Date dateTime, String place, String daibiaomianji, String pinzhong,
			String shengyuqi, String diaochazhushu, String youyazhushu, String youyazhulv, String youchiyachongshuliang,
			String wuchiyachongshuliang, String hejishuliang, String baizhuyaliang, String remark, Integer userId,
			String userName, String longitude, String latitude) {
		this.dateTime = dateTime;
		this.place = place;
		this.daibiaomianji = daibiaomianji;
		this.pinzhong = pinzhong;
		this.shengyuqi = shengyuqi;
		this.diaochazhushu = diaochazhushu;
		this.youyazhushu = youyazhushu;
		this.youyazhulv = youyazhulv;
		this.youchiyachongshuliang = youchiyachongshuliang;
		this.wuchiyachongshuliang = wuchiyachongshuliang;
		this.hejishuliang = hejishuliang;
		this.baizhuyaliang = baizhuyaliang;
		this.remark = remark;
		this.userId = userId;
		this.userName = userName;
		this.longitude = longitude;
		this.latitude = latitude;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Date getDateTime() {
		return this.dateTime;
	}

	public void setDateTime(Date dateTime) {
		this.dateTime = dateTime;
	}

	

	public String getPlace() {
		return this.place;
	}

	public void setPlace(String place) {
		this.place = place;
	}

	public String getDaibiaomianji() {
		return this.daibiaomianji;
	}

	public void setDaibiaomianji(String daibiaomianji) {
		this.daibiaomianji = daibiaomianji;
	}

	public String getPinzhong() {
		return this.pinzhong;
	}

	public void setPinzhong(String pinzhong) {
		this.pinzhong = pinzhong;
	}

	public String getShengyuqi() {
		return this.shengyuqi;
	}

	public void setShengyuqi(String shengyuqi) {
		this.shengyuqi = shengyuqi;
	}

	public String getDiaochazhushu() {
		return this.diaochazhushu;
	}

	public void setDiaochazhushu(String diaochazhushu) {
		this.diaochazhushu = diaochazhushu;
	}

	public String getYouyazhushu() {
		return this.youyazhushu;
	}

	public void setYouyazhushu(String youyazhushu) {
		this.youyazhushu = youyazhushu;
	}

	public String getYouyazhulv() {
		return this.youyazhulv;
	}

	public void setYouyazhulv(String youyazhulv) {
		this.youyazhulv = youyazhulv;
	}

	public String getYouchiyachongshuliang() {
		return this.youchiyachongshuliang;
	}

	public void setYouchiyachongshuliang(String youchiyachongshuliang) {
		this.youchiyachongshuliang = youchiyachongshuliang;
	}

	public String getWuchiyachongshuliang() {
		return this.wuchiyachongshuliang;
	}

	public void setWuchiyachongshuliang(String wuchiyachongshuliang) {
		this.wuchiyachongshuliang = wuchiyachongshuliang;
	}

	public String getHejishuliang() {
		return this.hejishuliang;
	}

	public void setHejishuliang(String hejishuliang) {
		this.hejishuliang = hejishuliang;
	}

	public String getBaizhuyaliang() {
		return this.baizhuyaliang;
	}

	public void setBaizhuyaliang(String baizhuyaliang) {
		this.baizhuyaliang = baizhuyaliang;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public String getLongitude() {
		return this.longitude;
	}

	public void setLongitude(String longitude) {
		this.longitude = longitude;
	}

	public String getLatitude() {
		return this.latitude;
	}

	public void setLatitude(String latitude) {
		this.latitude = latitude;
	}

}
