package com.wt.jiaduo.controller.pojovalid;
// Generated 2018-3-31 10:29:38 by Hibernate Tools 5.2.8.Final

import java.util.Date;

import javax.validation.constraints.NotNull;

/**
 * XiaomaiYexiubing generated by hbm2java
 */
public class XiaomaiYexiubingUpdateValid implements java.io.Serializable {
	@NotNull(message="id不能为空")
	private Integer id;
	private String place;
	private Date dateTime;
	private String serialNumber;
	private String variety;
	private String sowingDate;
	private String growthPeriod;
	private String fieldArea;
	private String allfieldConditions;
	private String checkArea;
	private String bladeDensity;
	private String monolithicLeafDensity;
	private String surveyBladenum;
	private String onsetBladenum;
	private String diseasedLeafrate;
	private String severity;
	private String diseaseIndex;
	private String reactive;
	private Integer userId;
	private String userName;
	private String longitude;
	private String latitude;

	public XiaomaiYexiubingUpdateValid() {
	}

	public XiaomaiYexiubingUpdateValid(String place,  Date dateTime, String serialNumber, String variety,
			String sowingDate, String growthPeriod, String fieldArea, String allfieldConditions, String checkArea,
			String bladeDensity, String monolithicLeafDensity, String surveyBladenum, String onsetBladenum,
			String diseasedLeafrate, String severity, String diseaseIndex, String reactive, Integer userId,
			String userName, String longitude, String latitude) {
		this.place = place;
		this.dateTime = dateTime;
		this.serialNumber = serialNumber;
		this.variety = variety;
		this.sowingDate = sowingDate;
		this.growthPeriod = growthPeriod;
		this.fieldArea = fieldArea;
		this.allfieldConditions = allfieldConditions;
		this.checkArea = checkArea;
		this.bladeDensity = bladeDensity;
		this.monolithicLeafDensity = monolithicLeafDensity;
		this.surveyBladenum = surveyBladenum;
		this.onsetBladenum = onsetBladenum;
		this.diseasedLeafrate = diseasedLeafrate;
		this.severity = severity;
		this.diseaseIndex = diseaseIndex;
		this.reactive = reactive;
		this.userId = userId;
		this.userName = userName;
		this.longitude = longitude;
		this.latitude = latitude;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getPlace() {
		return this.place;
	}

	public void setPlace(String place) {
		this.place = place;
	}

	

	public Date getDateTime() {
		return this.dateTime;
	}

	public void setDateTime(Date dateTime) {
		this.dateTime = dateTime;
	}

	public String getSerialNumber() {
		return this.serialNumber;
	}

	public void setSerialNumber(String serialNumber) {
		this.serialNumber = serialNumber;
	}

	public String getVariety() {
		return this.variety;
	}

	public void setVariety(String variety) {
		this.variety = variety;
	}

	public String getSowingDate() {
		return this.sowingDate;
	}

	public void setSowingDate(String sowingDate) {
		this.sowingDate = sowingDate;
	}

	public String getGrowthPeriod() {
		return this.growthPeriod;
	}

	public void setGrowthPeriod(String growthPeriod) {
		this.growthPeriod = growthPeriod;
	}

	public String getFieldArea() {
		return this.fieldArea;
	}

	public void setFieldArea(String fieldArea) {
		this.fieldArea = fieldArea;
	}

	public String getAllfieldConditions() {
		return this.allfieldConditions;
	}

	public void setAllfieldConditions(String allfieldConditions) {
		this.allfieldConditions = allfieldConditions;
	}

	public String getCheckArea() {
		return this.checkArea;
	}

	public void setCheckArea(String checkArea) {
		this.checkArea = checkArea;
	}

	public String getBladeDensity() {
		return this.bladeDensity;
	}

	public void setBladeDensity(String bladeDensity) {
		this.bladeDensity = bladeDensity;
	}

	public String getMonolithicLeafDensity() {
		return this.monolithicLeafDensity;
	}

	public void setMonolithicLeafDensity(String monolithicLeafDensity) {
		this.monolithicLeafDensity = monolithicLeafDensity;
	}

	public String getSurveyBladenum() {
		return this.surveyBladenum;
	}

	public void setSurveyBladenum(String surveyBladenum) {
		this.surveyBladenum = surveyBladenum;
	}

	public String getOnsetBladenum() {
		return this.onsetBladenum;
	}

	public void setOnsetBladenum(String onsetBladenum) {
		this.onsetBladenum = onsetBladenum;
	}

	public String getDiseasedLeafrate() {
		return this.diseasedLeafrate;
	}

	public void setDiseasedLeafrate(String diseasedLeafrate) {
		this.diseasedLeafrate = diseasedLeafrate;
	}

	public String getSeverity() {
		return this.severity;
	}

	public void setSeverity(String severity) {
		this.severity = severity;
	}

	public String getDiseaseIndex() {
		return this.diseaseIndex;
	}

	public void setDiseaseIndex(String diseaseIndex) {
		this.diseaseIndex = diseaseIndex;
	}

	public String getReactive() {
		return this.reactive;
	}

	public void setReactive(String reactive) {
		this.reactive = reactive;
	}

	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public String getLongitude() {
		return this.longitude;
	}

	public void setLongitude(String longitude) {
		this.longitude = longitude;
	}

	public String getLatitude() {
		return this.latitude;
	}

	public void setLatitude(String latitude) {
		this.latitude = latitude;
	}

}
