package com.wt.jiaduo.controller.pojovalid;
// Generated 2018-3-31 10:29:38 by Hibernate Tools 5.2.8.Final

import java.util.Date;

import org.springframework.format.annotation.DateTimeFormat;

/**
 * XiaomaiWenkubing generated by hbm2java
 */
public class XiaomaiWenkubingAddValid implements java.io.Serializable {

	@DateTimeFormat(pattern="yyyy-MM-dd HH:mm:ss")
	private Date dateTime;
	private String place;
	private String sowing;
	private String sakaguchi;
	private String growthPeriod;
	private String diseaseSurveynumofplants;
	private String diseaseNumofplants;
	private String diseaseRate;
	private String stemsSurveynumofplants;
	private String numofstems;
	private String numofstemsRate;
	private String severity0;
	private String severity1;
	private String severity2;
	private String severity3;
	private String severity4;
	private String severity5;
	private String diseaseIndex;
	private String remark;
	private Integer userId;
	private String userName;
	private String longitude;
	private String latitude;

	public XiaomaiWenkubingAddValid() {
	}

	public XiaomaiWenkubingAddValid(Date dateTime,  String place, String sowing, String sakaguchi,
			String growthPeriod, String diseaseSurveynumofplants, String diseaseNumofplants, String diseaseRate,
			String stemsSurveynumofplants, String numofstems, String numofstemsRate, String severity0, String severity1,
			String severity2, String severity3, String severity4, String severity5, String diseaseIndex, String remark,
			Integer userId, String userName, String longitude, String latitude) {
		this.dateTime = dateTime;
		this.place = place;
		this.sowing = sowing;
		this.sakaguchi = sakaguchi;
		this.growthPeriod = growthPeriod;
		this.diseaseSurveynumofplants = diseaseSurveynumofplants;
		this.diseaseNumofplants = diseaseNumofplants;
		this.diseaseRate = diseaseRate;
		this.stemsSurveynumofplants = stemsSurveynumofplants;
		this.numofstems = numofstems;
		this.numofstemsRate = numofstemsRate;
		this.severity0 = severity0;
		this.severity1 = severity1;
		this.severity2 = severity2;
		this.severity3 = severity3;
		this.severity4 = severity4;
		this.severity5 = severity5;
		this.diseaseIndex = diseaseIndex;
		this.remark = remark;
		this.userId = userId;
		this.userName = userName;
		this.longitude = longitude;
		this.latitude = latitude;
	}

	

	public Date getDateTime() {
		return this.dateTime;
	}

	public void setDateTime(Date dateTime) {
		this.dateTime = dateTime;
	}

	

	public String getPlace() {
		return this.place;
	}

	public void setPlace(String place) {
		this.place = place;
	}

	public String getSowing() {
		return this.sowing;
	}

	public void setSowing(String sowing) {
		this.sowing = sowing;
	}

	public String getSakaguchi() {
		return this.sakaguchi;
	}

	public void setSakaguchi(String sakaguchi) {
		this.sakaguchi = sakaguchi;
	}

	public String getGrowthPeriod() {
		return this.growthPeriod;
	}

	public void setGrowthPeriod(String growthPeriod) {
		this.growthPeriod = growthPeriod;
	}

	public String getDiseaseSurveynumofplants() {
		return this.diseaseSurveynumofplants;
	}

	public void setDiseaseSurveynumofplants(String diseaseSurveynumofplants) {
		this.diseaseSurveynumofplants = diseaseSurveynumofplants;
	}

	public String getDiseaseNumofplants() {
		return this.diseaseNumofplants;
	}

	public void setDiseaseNumofplants(String diseaseNumofplants) {
		this.diseaseNumofplants = diseaseNumofplants;
	}

	public String getDiseaseRate() {
		return this.diseaseRate;
	}

	public void setDiseaseRate(String diseaseRate) {
		this.diseaseRate = diseaseRate;
	}

	public String getStemsSurveynumofplants() {
		return this.stemsSurveynumofplants;
	}

	public void setStemsSurveynumofplants(String stemsSurveynumofplants) {
		this.stemsSurveynumofplants = stemsSurveynumofplants;
	}

	public String getNumofstems() {
		return this.numofstems;
	}

	public void setNumofstems(String numofstems) {
		this.numofstems = numofstems;
	}

	public String getNumofstemsRate() {
		return this.numofstemsRate;
	}

	public void setNumofstemsRate(String numofstemsRate) {
		this.numofstemsRate = numofstemsRate;
	}

	public String getSeverity0() {
		return this.severity0;
	}

	public void setSeverity0(String severity0) {
		this.severity0 = severity0;
	}

	public String getSeverity1() {
		return this.severity1;
	}

	public void setSeverity1(String severity1) {
		this.severity1 = severity1;
	}

	public String getSeverity2() {
		return this.severity2;
	}

	public void setSeverity2(String severity2) {
		this.severity2 = severity2;
	}

	public String getSeverity3() {
		return this.severity3;
	}

	public void setSeverity3(String severity3) {
		this.severity3 = severity3;
	}

	public String getSeverity4() {
		return this.severity4;
	}

	public void setSeverity4(String severity4) {
		this.severity4 = severity4;
	}

	public String getSeverity5() {
		return this.severity5;
	}

	public void setSeverity5(String severity5) {
		this.severity5 = severity5;
	}

	public String getDiseaseIndex() {
		return this.diseaseIndex;
	}

	public void setDiseaseIndex(String diseaseIndex) {
		this.diseaseIndex = diseaseIndex;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public String getLongitude() {
		return this.longitude;
	}

	public void setLongitude(String longitude) {
		this.longitude = longitude;
	}

	public String getLatitude() {
		return this.latitude;
	}

	public void setLatitude(String latitude) {
		this.latitude = latitude;
	}

}
