package com.wt.jiaduo.controller.pojovalid;
// Generated 2018-3-31 10:29:38 by Hibernate Tools 5.2.8.Final

import java.util.Date;

import javax.validation.constraints.NotNull;

import org.springframework.format.annotation.DateTimeFormat;

/**
 * XiaomaiTiaoxiubingHouqi generated by hbm2java
 */
public class XiaomaiTiaoxiubingHouqiUpdateValid implements java.io.Serializable {
	@NotNull(message="id不能为空")
	private Integer id;
	private String place;
	@DateTimeFormat(pattern="yyyy-MM-dd HH:mm:ss")
	private Date dateTime;
	private String variety;
	private String fieldNum;
	private String growthPeriod;
	private String typeField1Rate;
	private String typeField1Severity;
	private String typeField2Rate;
	private String typeField2Severity;
	private String typeField3Rate;
	private String typeField3Severity;
	private String typeField4Rate;
	private String typeField4Severity;
	private String typeField5Rate;
	private String typeField5Severity;
	private String typeAverageRate;
	private String typeAverageSeverity;
	private Integer userId;
	private String userName;
	private String longitude;
	private String latitude;
	private String remark;
	

	public String getRemark() {
		return remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public XiaomaiTiaoxiubingHouqiUpdateValid() {
	}

	public XiaomaiTiaoxiubingHouqiUpdateValid(String place,Date dateTime, String variety, String fieldNum,
			String growthPeriod, String typeField1Rate, String typeField1Severity, String typeField2Rate,
			String typeField2Severity, String typeField3Rate, String typeField3Severity, String typeField4Rate,
			String typeField4Severity, String typeField5Rate, String typeField5Severity, String typeAverageRate,
			String typeAverageSeverity, Integer userId, String userName, String longitude, String latitude) {
		this.place = place;
		this.dateTime = dateTime;
		this.variety = variety;
		this.fieldNum = fieldNum;
		this.growthPeriod = growthPeriod;
		this.typeField1Rate = typeField1Rate;
		this.typeField1Severity = typeField1Severity;
		this.typeField2Rate = typeField2Rate;
		this.typeField2Severity = typeField2Severity;
		this.typeField3Rate = typeField3Rate;
		this.typeField3Severity = typeField3Severity;
		this.typeField4Rate = typeField4Rate;
		this.typeField4Severity = typeField4Severity;
		this.typeField5Rate = typeField5Rate;
		this.typeField5Severity = typeField5Severity;
		this.typeAverageRate = typeAverageRate;
		this.typeAverageSeverity = typeAverageSeverity;
		this.userId = userId;
		this.userName = userName;
		this.longitude = longitude;
		this.latitude = latitude;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getPlace() {
		return this.place;
	}

	public void setPlace(String place) {
		this.place = place;
	}

	

	public Date getDateTime() {
		return this.dateTime;
	}

	public void setDateTime(Date dateTime) {
		this.dateTime = dateTime;
	}

	public String getVariety() {
		return this.variety;
	}

	public void setVariety(String variety) {
		this.variety = variety;
	}

	public String getFieldNum() {
		return this.fieldNum;
	}

	public void setFieldNum(String fieldNum) {
		this.fieldNum = fieldNum;
	}

	public String getGrowthPeriod() {
		return this.growthPeriod;
	}

	public void setGrowthPeriod(String growthPeriod) {
		this.growthPeriod = growthPeriod;
	}

	public String getTypeField1Rate() {
		return this.typeField1Rate;
	}

	public void setTypeField1Rate(String typeField1Rate) {
		this.typeField1Rate = typeField1Rate;
	}

	public String getTypeField1Severity() {
		return this.typeField1Severity;
	}

	public void setTypeField1Severity(String typeField1Severity) {
		this.typeField1Severity = typeField1Severity;
	}

	public String getTypeField2Rate() {
		return this.typeField2Rate;
	}

	public void setTypeField2Rate(String typeField2Rate) {
		this.typeField2Rate = typeField2Rate;
	}

	public String getTypeField2Severity() {
		return this.typeField2Severity;
	}

	public void setTypeField2Severity(String typeField2Severity) {
		this.typeField2Severity = typeField2Severity;
	}

	public String getTypeField3Rate() {
		return this.typeField3Rate;
	}

	public void setTypeField3Rate(String typeField3Rate) {
		this.typeField3Rate = typeField3Rate;
	}

	public String getTypeField3Severity() {
		return this.typeField3Severity;
	}

	public void setTypeField3Severity(String typeField3Severity) {
		this.typeField3Severity = typeField3Severity;
	}

	public String getTypeField4Rate() {
		return this.typeField4Rate;
	}

	public void setTypeField4Rate(String typeField4Rate) {
		this.typeField4Rate = typeField4Rate;
	}

	public String getTypeField4Severity() {
		return this.typeField4Severity;
	}

	public void setTypeField4Severity(String typeField4Severity) {
		this.typeField4Severity = typeField4Severity;
	}

	public String getTypeField5Rate() {
		return this.typeField5Rate;
	}

	public void setTypeField5Rate(String typeField5Rate) {
		this.typeField5Rate = typeField5Rate;
	}

	public String getTypeField5Severity() {
		return this.typeField5Severity;
	}

	public void setTypeField5Severity(String typeField5Severity) {
		this.typeField5Severity = typeField5Severity;
	}

	public String getTypeAverageRate() {
		return this.typeAverageRate;
	}

	public void setTypeAverageRate(String typeAverageRate) {
		this.typeAverageRate = typeAverageRate;
	}

	public String getTypeAverageSeverity() {
		return this.typeAverageSeverity;
	}

	public void setTypeAverageSeverity(String typeAverageSeverity) {
		this.typeAverageSeverity = typeAverageSeverity;
	}

	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public String getLongitude() {
		return this.longitude;
	}

	public void setLongitude(String longitude) {
		this.longitude = longitude;
	}

	public String getLatitude() {
		return this.latitude;
	}

	public void setLatitude(String latitude) {
		this.latitude = latitude;
	}

}
