package com.wt.jiaduo.controller.pojovalid;
// Generated 2018-3-31 10:29:38 by Hibernate Tools 5.2.8.Final

import java.util.Date;

import org.springframework.format.annotation.DateTimeFormat;

/**
 * XiaomaiCongaibingBingqingpucha generated by hbm2java
 */
public class XiaomaiCongaibingBingqingpuchaAddValid implements java.io.Serializable {

	@DateTimeFormat(pattern="yyyy-MM-dd HH:mm:ss")
	private Date dateTime;
	private String place;
	private String zhongzhifangshi;
	private String diaochamianji;
	private String fabingmianji;
	private String bingzhulv1;
	private String bingzhulv1zhi3;
	private String bingzhulv3zhi10;
	private String bingzhulv10zhi20;
	private String bingzhulv20zhi50;
	private String bingzhulv50;
	private String huizhongmianji;
	private String remark;
	private Integer userId;
	private String userName;
	private String longitude;
	private String latitude;

	public XiaomaiCongaibingBingqingpuchaAddValid() {
	}

	public XiaomaiCongaibingBingqingpuchaAddValid(Date dateTime,  String place, String zhongzhifangshi,
			String diaochamianji, String fabingmianji, String bingzhulv1, String bingzhulv1zhi3, String bingzhulv3zhi10,
			String bingzhulv10zhi20, String bingzhulv20zhi50, String bingzhulv50, String huizhongmianji, String remark,
			Integer userId, String userName, String longitude, String latitude) {
		this.dateTime = dateTime;
		this.place = place;
		this.zhongzhifangshi = zhongzhifangshi;
		this.diaochamianji = diaochamianji;
		this.fabingmianji = fabingmianji;
		this.bingzhulv1 = bingzhulv1;
		this.bingzhulv1zhi3 = bingzhulv1zhi3;
		this.bingzhulv3zhi10 = bingzhulv3zhi10;
		this.bingzhulv10zhi20 = bingzhulv10zhi20;
		this.bingzhulv20zhi50 = bingzhulv20zhi50;
		this.bingzhulv50 = bingzhulv50;
		this.huizhongmianji = huizhongmianji;
		this.remark = remark;
		this.userId = userId;
		this.userName = userName;
		this.longitude = longitude;
		this.latitude = latitude;
	}

	

	public Date getDateTime() {
		return this.dateTime;
	}

	public void setDateTime(Date dateTime) {
		this.dateTime = dateTime;
	}

	

	public String getPlace() {
		return this.place;
	}

	public void setPlace(String place) {
		this.place = place;
	}

	public String getZhongzhifangshi() {
		return this.zhongzhifangshi;
	}

	public void setZhongzhifangshi(String zhongzhifangshi) {
		this.zhongzhifangshi = zhongzhifangshi;
	}

	public String getDiaochamianji() {
		return this.diaochamianji;
	}

	public void setDiaochamianji(String diaochamianji) {
		this.diaochamianji = diaochamianji;
	}

	public String getFabingmianji() {
		return this.fabingmianji;
	}

	public void setFabingmianji(String fabingmianji) {
		this.fabingmianji = fabingmianji;
	}

	public String getBingzhulv1() {
		return this.bingzhulv1;
	}

	public void setBingzhulv1(String bingzhulv1) {
		this.bingzhulv1 = bingzhulv1;
	}

	public String getBingzhulv1zhi3() {
		return this.bingzhulv1zhi3;
	}

	public void setBingzhulv1zhi3(String bingzhulv1zhi3) {
		this.bingzhulv1zhi3 = bingzhulv1zhi3;
	}

	public String getBingzhulv3zhi10() {
		return this.bingzhulv3zhi10;
	}

	public void setBingzhulv3zhi10(String bingzhulv3zhi10) {
		this.bingzhulv3zhi10 = bingzhulv3zhi10;
	}

	public String getBingzhulv10zhi20() {
		return this.bingzhulv10zhi20;
	}

	public void setBingzhulv10zhi20(String bingzhulv10zhi20) {
		this.bingzhulv10zhi20 = bingzhulv10zhi20;
	}

	public String getBingzhulv20zhi50() {
		return this.bingzhulv20zhi50;
	}

	public void setBingzhulv20zhi50(String bingzhulv20zhi50) {
		this.bingzhulv20zhi50 = bingzhulv20zhi50;
	}

	public String getBingzhulv50() {
		return this.bingzhulv50;
	}

	public void setBingzhulv50(String bingzhulv50) {
		this.bingzhulv50 = bingzhulv50;
	}

	public String getHuizhongmianji() {
		return this.huizhongmianji;
	}

	public void setHuizhongmianji(String huizhongmianji) {
		this.huizhongmianji = huizhongmianji;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public String getLongitude() {
		return this.longitude;
	}

	public void setLongitude(String longitude) {
		this.longitude = longitude;
	}

	public String getLatitude() {
		return this.latitude;
	}

	public void setLatitude(String latitude) {
		this.latitude = latitude;
	}

}
