package com.wt.jiaduo.controller.pojovalid;
// Generated 2018-3-31 10:29:38 by Hibernate Tools 5.2.8.Final

import java.util.Date;

import javax.validation.constraints.NotNull;

/**
 * XiaomaiSanheisuibing generated by hbm2java
 */
public class XiaomaiSanheisuibingUpdateValid implements java.io.Serializable {
	@NotNull(message="id不能为空")
	private Integer id;
	private Date dateTime;
	private String place;
	private String varietyName;
	private String representativeArea;
	private String surveyPointnum;
	private String diseasePointnum;
	private String diseasepointRate;
	private String surveyMaiyenum;
	private String diseaseMaiyenum;
	private String diseasemaiyeRate;
	private String remark;
	private Integer userId;
	private String userName;
	private String longitude;
	private String latitude;

	public XiaomaiSanheisuibingUpdateValid() {
	}

	public XiaomaiSanheisuibingUpdateValid(Date dateTime, String place, String varietyName,
			String representativeArea, String surveyPointnum, String diseasePointnum, String diseasepointRate,
			String surveyMaiyenum, String diseaseMaiyenum, String diseasemaiyeRate, String remark, Integer userId,
			String userName, String longitude, String latitude) {
		this.dateTime = dateTime;
		this.place = place;
		this.varietyName = varietyName;
		this.representativeArea = representativeArea;
		this.surveyPointnum = surveyPointnum;
		this.diseasePointnum = diseasePointnum;
		this.diseasepointRate = diseasepointRate;
		this.surveyMaiyenum = surveyMaiyenum;
		this.diseaseMaiyenum = diseaseMaiyenum;
		this.diseasemaiyeRate = diseasemaiyeRate;
		this.remark = remark;
		this.userId = userId;
		this.userName = userName;
		this.longitude = longitude;
		this.latitude = latitude;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Date getDateTime() {
		return this.dateTime;
	}

	public void setDateTime(Date dateTime) {
		this.dateTime = dateTime;
	}

	public String getPlace() {
		return this.place;
	}

	public void setPlace(String place) {
		this.place = place;
	}

	

	public String getVarietyName() {
		return this.varietyName;
	}

	public void setVarietyName(String varietyName) {
		this.varietyName = varietyName;
	}

	public String getRepresentativeArea() {
		return this.representativeArea;
	}

	public void setRepresentativeArea(String representativeArea) {
		this.representativeArea = representativeArea;
	}

	public String getSurveyPointnum() {
		return this.surveyPointnum;
	}

	public void setSurveyPointnum(String surveyPointnum) {
		this.surveyPointnum = surveyPointnum;
	}

	public String getDiseasePointnum() {
		return this.diseasePointnum;
	}

	public void setDiseasePointnum(String diseasePointnum) {
		this.diseasePointnum = diseasePointnum;
	}

	public String getDiseasepointRate() {
		return this.diseasepointRate;
	}

	public void setDiseasepointRate(String diseasepointRate) {
		this.diseasepointRate = diseasepointRate;
	}

	public String getSurveyMaiyenum() {
		return this.surveyMaiyenum;
	}

	public void setSurveyMaiyenum(String surveyMaiyenum) {
		this.surveyMaiyenum = surveyMaiyenum;
	}

	public String getDiseaseMaiyenum() {
		return this.diseaseMaiyenum;
	}

	public void setDiseaseMaiyenum(String diseaseMaiyenum) {
		this.diseaseMaiyenum = diseaseMaiyenum;
	}

	public String getDiseasemaiyeRate() {
		return this.diseasemaiyeRate;
	}

	public void setDiseasemaiyeRate(String diseasemaiyeRate) {
		this.diseasemaiyeRate = diseasemaiyeRate;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public String getLongitude() {
		return this.longitude;
	}

	public void setLongitude(String longitude) {
		this.longitude = longitude;
	}

	public String getLatitude() {
		return this.latitude;
	}

	public void setLatitude(String latitude) {
		this.latitude = latitude;
	}

}
