package com.wt.jiaduo.controller.pojovalid;
// Generated 2018-3-31 10:29:38 by Hibernate Tools 5.2.8.Final

import java.util.Date;

import javax.validation.constraints.NotNull;

import org.springframework.format.annotation.DateTimeFormat;

/**
 * XiaomaiBaifenbing generated by hbm2java
 */
public class XiaomaiBaifenbingUpdateValid implements java.io.Serializable {
	@NotNull(message="id不能为空")
	private Integer id;
	@DateTimeFormat(pattern="yyyy-MM-dd HH:mm:ss")
	private Date dateTime;
	private String place;
	private String varietyName;
	private String sowingDate;
	private String growthPeriod;
	private String fieldArea;
	private String checkArea;
	private String numberofinvestigations;
	private String numberofdiseasedplants;
	private String diseaseRate;
	private String surveyBladenum;
	private String onsetBladenum;
	private String diseasedLeafrate;
	private String severity;
	private String diseaseIndex;
	private String diseasepointRate;
	private Integer userId;
	private String userName;
	private String longitude;
	private String latitude;
	private String remark;

	public XiaomaiBaifenbingUpdateValid() {
	}

	public XiaomaiBaifenbingUpdateValid(Date dateTime, String place, String varietyName, String sowingDate,
			String growthPeriod, String fieldArea, String checkArea, String numberofinvestigations,
			String numberofdiseasedplants, String diseaseRate, String surveyBladenum, String onsetBladenum,
			String diseasedLeafrate, String severity, String diseaseIndex, String diseasepointRate, Integer userId,
			String userName, String longitude, String latitude, String remark) {
		this.dateTime = dateTime;
		this.place = place;
		this.varietyName = varietyName;
		this.sowingDate = sowingDate;
		this.growthPeriod = growthPeriod;
		this.fieldArea = fieldArea;
		this.checkArea = checkArea;
		this.numberofinvestigations = numberofinvestigations;
		this.numberofdiseasedplants = numberofdiseasedplants;
		this.diseaseRate = diseaseRate;
		this.surveyBladenum = surveyBladenum;
		this.onsetBladenum = onsetBladenum;
		this.diseasedLeafrate = diseasedLeafrate;
		this.severity = severity;
		this.diseaseIndex = diseaseIndex;
		this.diseasepointRate = diseasepointRate;
		this.userId = userId;
		this.userName = userName;
		this.longitude = longitude;
		this.latitude = latitude;
		this.remark = remark;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Date getDateTime() {
		return this.dateTime;
	}

	public void setDateTime(Date dateTime) {
		this.dateTime = dateTime;
	}

	public String getPlace() {
		return this.place;
	}

	public void setPlace(String place) {
		this.place = place;
	}

	

	public String getVarietyName() {
		return this.varietyName;
	}

	public void setVarietyName(String varietyName) {
		this.varietyName = varietyName;
	}

	public String getSowingDate() {
		return this.sowingDate;
	}

	public void setSowingDate(String sowingDate) {
		this.sowingDate = sowingDate;
	}

	public String getGrowthPeriod() {
		return this.growthPeriod;
	}

	public void setGrowthPeriod(String growthPeriod) {
		this.growthPeriod = growthPeriod;
	}

	public String getFieldArea() {
		return this.fieldArea;
	}

	public void setFieldArea(String fieldArea) {
		this.fieldArea = fieldArea;
	}

	public String getCheckArea() {
		return this.checkArea;
	}

	public void setCheckArea(String checkArea) {
		this.checkArea = checkArea;
	}

	public String getNumberofinvestigations() {
		return this.numberofinvestigations;
	}

	public void setNumberofinvestigations(String numberofinvestigations) {
		this.numberofinvestigations = numberofinvestigations;
	}

	public String getNumberofdiseasedplants() {
		return this.numberofdiseasedplants;
	}

	public void setNumberofdiseasedplants(String numberofdiseasedplants) {
		this.numberofdiseasedplants = numberofdiseasedplants;
	}

	public String getDiseaseRate() {
		return this.diseaseRate;
	}

	public void setDiseaseRate(String diseaseRate) {
		this.diseaseRate = diseaseRate;
	}

	public String getSurveyBladenum() {
		return this.surveyBladenum;
	}

	public void setSurveyBladenum(String surveyBladenum) {
		this.surveyBladenum = surveyBladenum;
	}

	public String getOnsetBladenum() {
		return this.onsetBladenum;
	}

	public void setOnsetBladenum(String onsetBladenum) {
		this.onsetBladenum = onsetBladenum;
	}

	public String getDiseasedLeafrate() {
		return this.diseasedLeafrate;
	}

	public void setDiseasedLeafrate(String diseasedLeafrate) {
		this.diseasedLeafrate = diseasedLeafrate;
	}

	public String getSeverity() {
		return this.severity;
	}

	public void setSeverity(String severity) {
		this.severity = severity;
	}

	public String getDiseaseIndex() {
		return this.diseaseIndex;
	}

	public void setDiseaseIndex(String diseaseIndex) {
		this.diseaseIndex = diseaseIndex;
	}

	public String getDiseasepointRate() {
		return this.diseasepointRate;
	}

	public void setDiseasepointRate(String diseasepointRate) {
		this.diseasepointRate = diseasepointRate;
	}

	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public String getLongitude() {
		return this.longitude;
	}

	public void setLongitude(String longitude) {
		this.longitude = longitude;
	}

	public String getLatitude() {
		return this.latitude;
	}

	public void setLatitude(String latitude) {
		this.latitude = latitude;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

}
