package com.wt.jiaduo.controller.pojovalid;
// Generated 2018-3-31 10:29:38 by Hibernate Tools 5.2.8.Final

import java.util.Date;

/**
 * XiaomaiCongaibingYoucepufabinglv generated by hbm2java
 */
public class XiaomaiCongaibingYoucepufabinglvAddValid implements java.io.Serializable {

	
	private Date dateTime;
	private String place;
	private String qianchazuowu;
	private String xiaomaipinzhong;
	private String buzhongriqi;
	private String diaochamiaoshu;
	private String fabingmiaoshu;
	private String bingzhulv;
	private String remark;
	private Integer userId;
	private String userName;
	private String longitude;
	private String latitude;

	public XiaomaiCongaibingYoucepufabinglvAddValid() {
	}

	public XiaomaiCongaibingYoucepufabinglvAddValid(Date dateTime,  String place, String qianchazuowu,
			String xiaomaipinzhong, String buzhongriqi, String diaochamiaoshu, String fabingmiaoshu, String bingzhulv,
			String remark, Integer userId, String userName, String longitude, String latitude) {
		this.dateTime = dateTime;
		this.place = place;
		this.qianchazuowu = qianchazuowu;
		this.xiaomaipinzhong = xiaomaipinzhong;
		this.buzhongriqi = buzhongriqi;
		this.diaochamiaoshu = diaochamiaoshu;
		this.fabingmiaoshu = fabingmiaoshu;
		this.bingzhulv = bingzhulv;
		this.remark = remark;
		this.userId = userId;
		this.userName = userName;
		this.longitude = longitude;
		this.latitude = latitude;
	}

	

	public Date getDateTime() {
		return this.dateTime;
	}

	public void setDateTime(Date dateTime) {
		this.dateTime = dateTime;
	}

	

	public String getPlace() {
		return this.place;
	}

	public void setPlace(String place) {
		this.place = place;
	}

	public String getQianchazuowu() {
		return this.qianchazuowu;
	}

	public void setQianchazuowu(String qianchazuowu) {
		this.qianchazuowu = qianchazuowu;
	}

	public String getXiaomaipinzhong() {
		return this.xiaomaipinzhong;
	}

	public void setXiaomaipinzhong(String xiaomaipinzhong) {
		this.xiaomaipinzhong = xiaomaipinzhong;
	}

	public String getBuzhongriqi() {
		return this.buzhongriqi;
	}

	public void setBuzhongriqi(String buzhongriqi) {
		this.buzhongriqi = buzhongriqi;
	}

	public String getDiaochamiaoshu() {
		return this.diaochamiaoshu;
	}

	public void setDiaochamiaoshu(String diaochamiaoshu) {
		this.diaochamiaoshu = diaochamiaoshu;
	}

	public String getFabingmiaoshu() {
		return this.fabingmiaoshu;
	}

	public void setFabingmiaoshu(String fabingmiaoshu) {
		this.fabingmiaoshu = fabingmiaoshu;
	}

	public String getBingzhulv() {
		return this.bingzhulv;
	}

	public void setBingzhulv(String bingzhulv) {
		this.bingzhulv = bingzhulv;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public String getLongitude() {
		return this.longitude;
	}

	public void setLongitude(String longitude) {
		this.longitude = longitude;
	}

	public String getLatitude() {
		return this.latitude;
	}

	public void setLatitude(String latitude) {
		this.latitude = latitude;
	}

}
