package com.wt.jiaduo.controller.pojovalid;
// Generated 2018-3-31 10:29:38 by Hibernate Tools 5.2.8.Final

import java.util.Date;

import javax.validation.constraints.NotNull;

/**
 * XiaomaiXijiangchongtaotu generated by hbm2java
 */
public class XiaomaiXijiangchongtaotuUpdateValid implements java.io.Serializable {
	@NotNull(message="id不能为空")
	private Integer id;
	private Date dateTime;
	private String place;
	private String dishi;
	private String tuzhi;
	private String qiancha;
	private String qutuyangfangshu;
	private String youchongyangfangshu;
	private String yangfang5;
	private String huodongyouchongshu;
	private String yuanjianshu;
	private String heji;
	private String pingjunmidu;
	private String zuigaomidu;
	private Integer userId;
	private String userName;
	private String longitude;
	private String latitude;

	public XiaomaiXijiangchongtaotuUpdateValid() {
	}

	public XiaomaiXijiangchongtaotuUpdateValid(Date dateTime,  String place, String dishi, String tuzhi,
			String qiancha, String qutuyangfangshu, String youchongyangfangshu, String yangfang5,
			String huodongyouchongshu, String yuanjianshu, String heji, String pingjunmidu, String zuigaomidu,
			Integer userId, String userName, String longitude, String latitude) {
		this.dateTime = dateTime;
		this.place = place;
		this.dishi = dishi;
		this.tuzhi = tuzhi;
		this.qiancha = qiancha;
		this.qutuyangfangshu = qutuyangfangshu;
		this.youchongyangfangshu = youchongyangfangshu;
		this.yangfang5 = yangfang5;
		this.huodongyouchongshu = huodongyouchongshu;
		this.yuanjianshu = yuanjianshu;
		this.heji = heji;
		this.pingjunmidu = pingjunmidu;
		this.zuigaomidu = zuigaomidu;
		this.userId = userId;
		this.userName = userName;
		this.longitude = longitude;
		this.latitude = latitude;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Date getDateTime() {
		return this.dateTime;
	}

	public void setDateTime(Date dateTime) {
		this.dateTime = dateTime;
	}

	

	public String getPlace() {
		return this.place;
	}

	public void setPlace(String place) {
		this.place = place;
	}

	public String getDishi() {
		return this.dishi;
	}

	public void setDishi(String dishi) {
		this.dishi = dishi;
	}

	public String getTuzhi() {
		return this.tuzhi;
	}

	public void setTuzhi(String tuzhi) {
		this.tuzhi = tuzhi;
	}

	public String getQiancha() {
		return this.qiancha;
	}

	public void setQiancha(String qiancha) {
		this.qiancha = qiancha;
	}

	public String getQutuyangfangshu() {
		return this.qutuyangfangshu;
	}

	public void setQutuyangfangshu(String qutuyangfangshu) {
		this.qutuyangfangshu = qutuyangfangshu;
	}

	public String getYouchongyangfangshu() {
		return this.youchongyangfangshu;
	}

	public void setYouchongyangfangshu(String youchongyangfangshu) {
		this.youchongyangfangshu = youchongyangfangshu;
	}

	public String getYangfang5() {
		return this.yangfang5;
	}

	public void setYangfang5(String yangfang5) {
		this.yangfang5 = yangfang5;
	}

	public String getHuodongyouchongshu() {
		return this.huodongyouchongshu;
	}

	public void setHuodongyouchongshu(String huodongyouchongshu) {
		this.huodongyouchongshu = huodongyouchongshu;
	}

	public String getYuanjianshu() {
		return this.yuanjianshu;
	}

	public void setYuanjianshu(String yuanjianshu) {
		this.yuanjianshu = yuanjianshu;
	}

	public String getHeji() {
		return this.heji;
	}

	public void setHeji(String heji) {
		this.heji = heji;
	}

	public String getPingjunmidu() {
		return this.pingjunmidu;
	}

	public void setPingjunmidu(String pingjunmidu) {
		this.pingjunmidu = pingjunmidu;
	}

	public String getZuigaomidu() {
		return this.zuigaomidu;
	}

	public void setZuigaomidu(String zuigaomidu) {
		this.zuigaomidu = zuigaomidu;
	}

	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public String getLongitude() {
		return this.longitude;
	}

	public void setLongitude(String longitude) {
		this.longitude = longitude;
	}

	public String getLatitude() {
		return this.latitude;
	}

	public void setLatitude(String latitude) {
		this.latitude = latitude;
	}

}
