package com.wt.jiaduo.controller.pojovalid;
// Generated 2018-3-31 10:29:38 by Hibernate Tools 5.2.8.Final

import java.util.Date;

/**
 * XiaomaiTiaoxiubingYuexia generated by hbm2java
 */
public class XiaomaiTiaoxiubingYuexiaAddValid implements java.io.Serializable {

	
	private Date dateTime;
	private String place;
	private String serialNumber;
	private String lateripeningArea;
	private String type;
	private String sowing;
	private String prevalenceRate;
	private String severity1;
	private String spontaneousArea;
	private String previousType;
	private String currentType;
	private String spontaneousDensity;
	private String diseaseRate;
	private String severity2;
	private String remark;
	private Integer userId;
	private String userName;
	private String longitude;
	private String latitude;

	public XiaomaiTiaoxiubingYuexiaAddValid() {
	}

	public XiaomaiTiaoxiubingYuexiaAddValid(Date dateTime,  String place, String serialNumber,
			String lateripeningArea, String type, String sowing, String prevalenceRate, String severity1,
			String spontaneousArea, String previousType, String currentType, String spontaneousDensity,
			String diseaseRate, String severity2, String remark, Integer userId, String userName, String longitude,
			String latitude) {
		this.dateTime = dateTime;
		this.place = place;
		this.serialNumber = serialNumber;
		this.lateripeningArea = lateripeningArea;
		this.type = type;
		this.sowing = sowing;
		this.prevalenceRate = prevalenceRate;
		this.severity1 = severity1;
		this.spontaneousArea = spontaneousArea;
		this.previousType = previousType;
		this.currentType = currentType;
		this.spontaneousDensity = spontaneousDensity;
		this.diseaseRate = diseaseRate;
		this.severity2 = severity2;
		this.remark = remark;
		this.userId = userId;
		this.userName = userName;
		this.longitude = longitude;
		this.latitude = latitude;
	}


	public Date getDateTime() {
		return this.dateTime;
	}

	public void setDateTime(Date dateTime) {
		this.dateTime = dateTime;
	}

	

	public String getPlace() {
		return this.place;
	}

	public void setPlace(String place) {
		this.place = place;
	}

	public String getSerialNumber() {
		return this.serialNumber;
	}

	public void setSerialNumber(String serialNumber) {
		this.serialNumber = serialNumber;
	}

	public String getLateripeningArea() {
		return this.lateripeningArea;
	}

	public void setLateripeningArea(String lateripeningArea) {
		this.lateripeningArea = lateripeningArea;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public String getSowing() {
		return this.sowing;
	}

	public void setSowing(String sowing) {
		this.sowing = sowing;
	}

	public String getPrevalenceRate() {
		return this.prevalenceRate;
	}

	public void setPrevalenceRate(String prevalenceRate) {
		this.prevalenceRate = prevalenceRate;
	}

	public String getSeverity1() {
		return this.severity1;
	}

	public void setSeverity1(String severity1) {
		this.severity1 = severity1;
	}

	public String getSpontaneousArea() {
		return this.spontaneousArea;
	}

	public void setSpontaneousArea(String spontaneousArea) {
		this.spontaneousArea = spontaneousArea;
	}

	public String getPreviousType() {
		return this.previousType;
	}

	public void setPreviousType(String previousType) {
		this.previousType = previousType;
	}

	public String getCurrentType() {
		return this.currentType;
	}

	public void setCurrentType(String currentType) {
		this.currentType = currentType;
	}

	public String getSpontaneousDensity() {
		return this.spontaneousDensity;
	}

	public void setSpontaneousDensity(String spontaneousDensity) {
		this.spontaneousDensity = spontaneousDensity;
	}

	public String getDiseaseRate() {
		return this.diseaseRate;
	}

	public void setDiseaseRate(String diseaseRate) {
		this.diseaseRate = diseaseRate;
	}

	public String getSeverity2() {
		return this.severity2;
	}

	public void setSeverity2(String severity2) {
		this.severity2 = severity2;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public String getLongitude() {
		return this.longitude;
	}

	public void setLongitude(String longitude) {
		this.longitude = longitude;
	}

	public String getLatitude() {
		return this.latitude;
	}

	public void setLatitude(String latitude) {
		this.latitude = latitude;
	}

}
